apiVersion: v1
kind: Service
metadata:
  name: data-generator
  labels:
    app: data-generator
spec:
  selector:
    app: data-generator
  ports:
    - name: metrics
      port: 8000
      targetPort: metrics
