features:
  atm_withdrawal_6h:
    sql: |
      SELECT
        account_id,
        customer_id,
        card_id,
        SUM(amount) as total_amount,
        COUNT(*) as total_tx
      FROM atm_withdrawal
      WHERE card_id = '{card_id}'
        AND "timestamp" >= NOW() - 6 * 60 * 60 * 1000
      GROUP BY account_id, customer_id, card_id
    entities:
      - card_id
  login_attempted_6h:
    sql: |
      SELECT
          customer_id,
          device_id,
          COUNT(*) AS no_attempts,
          DISTINCTCOUNT(country) AS no_countries,
          ARRAY_AGG(country, 'STRING', true) AS countires
      FROM login_attempted
      WHERE 
          "timestamp" > NOW() - 6 * 60 * 60 * 1000
          AND customer_id = '{customer_id}'
          AND device_id = '{device_id}'
      GROUP BY customer_id, device_id
    entities:
      - customer_id
      - device_id
  payment_6h_batch:
    sql: |
      SELECT *
      FROM payment_6h_batch
      WHERE account_id = '{account_id}'
      AND card_id = '{card_id}'
    entities:
      - account_id
      - card_id
  payment_6h:
    sql: |
      with transactions as (
        select
            id
            ,"timestamp"
            ,account_id
            ,amount
            ,currency
            ,'WITHDRAWAL' as transaction_type
        from atm_withdrawal
        where account_id = '{account_id}'
        and "timestamp" >= NOW() - 6 * 60 * 60 * 1000
        union all
        select
            id
            ,"timestamp"
            ,account_id
            ,amount
            ,currency
            ,'CARD_PAYMENT' as transaction_type
        from payment_authorised
        where account_id = '{account_id}'
        and "timestamp" >= NOW() - 6 * 60 * 60 * 1000
        union all
        select
            id
            ,"timestamp"
            ,cast(destination_account_id as bigint) as account_id
            ,amount
            ,currency
            ,'TRANSFER' as transaction_type
        from transfer_completed
        where destination_account_id = '{account_id}'
        and "timestamp" >= NOW() - 6 * 60 * 60 * 1000
        union all
        select
            id
            ,"timestamp"
            ,cast(source_account_id as bigint) as account_id
            ,amount
            ,currency
            ,'TRANSFER' as transaction_type
        from transfer_completed
        where source_account_id = '{account_id}'
        and "timestamp" >= NOW() - 6 * 60 * 60 * 1000
      )
      select
        count(*) as tx_count
        ,sum(amount) as tx_sum
        ,max(amount) as tx_max
        ,min(amount) as tx_min
        
        ,sum(case when transaction_type = 'WITHDRAWAL' then 1 else 0 end) as withdrawal_count
        ,sum(case when transaction_type = 'WITHDRAWAL' then amount else 0 end) as withdrawal_sum
        ,max(case when transaction_type = 'WITHDRAWAL' then amount end) as withdrawal_max
        ,min(case when transaction_type = 'WITHDRAWAL' then amount end) as withdrawal_min
    
        ,sum(case when transaction_type = 'CARD_PAYMENT' then 1 else 0 end) as card_count
        ,sum(case when transaction_type = 'CARD_PAYMENT' then amount else 0 end) as card_sum
        ,max(case when transaction_type = 'CARD_PAYMENT' then amount end) as card_max
        ,min(case when transaction_type = 'CARD_PAYMENT' then amount end) as card_min
        
        ,sum(case when transaction_type = 'TRANSFER' then 1 else 0 end) as transfer_count
        ,sum(case when transaction_type = 'TRANSFER' then amount else 0 end) as transfer_sum
        ,max(case when transaction_type = 'TRANSFER' then amount end) as transfer_max
        ,min(case when transaction_type = 'TRANSFER' then amount end) as transfer_min
      from transactions;
    entities:
      - account_id
    multi_stage_engine: true
  customer_payment_6h:
    sql: |
      with customer_created_filtered as (
        select
          id
          ,created_at
          ,date_of_birth
          ,occupation
        from customer_created
        where id = '{customer_id}'
      ),
      customer_updated_filtered as (
        select 
          id
          ,created_at
          ,date_of_birth
          ,occupation
        from customer_details_updated
        where id = '{customer_id}'
      ),
      customer as (
        select
          id
          ,created_at
          ,occupation
          ,0 as rank
        from customer_created_filtered
        union all
        select
          id
          ,created_at
          ,occupation
          ,1 as rank
        from customer_updated_filtered
      ),
      current_customer as (
        select
          id
          ,created_at
          ,occupation
          ,rank
        from (
          select
            *
            ,row_number() over (order by created_at desc, rank desc) as rn
          from customer
        )
        where rn = 1
      ),
      all_customer_details as (
        select
          cur.id as id
          ,cur.created_at as last_updated
          ,cur.occupation as current_occupation
          ,cc.date_of_birth as date_of_birth
          ,cc.created_at as customer_created_at
          ,cu.customer_updates as customer_updates
        from current_customer cur
          cross join customer_created_filtered cc
          cross join (
            select count(*) as customer_updates
            from customer_updated_filtered
          ) cu
      ),
      customer_payment as (
        select 
          acd.id as customer_id
          ,acd.last_updated
          ,acd.current_occupation
          ,acd.date_of_birth
          ,acd.customer_created_at
          ,acd.customer_updates
          ,p."timestamp"
          ,p.amount
          ,p.currency
        from all_customer_details acd
          left join payment_authorised p on acd.id = p.customer_id
          and p.currency = 'GBP'
          and p."timestamp" >= NOW() - interval '6' hour
      )
      select
        last_updated
        ,current_occupation 
        ,date_of_birth 
        ,customer_created_at
        ,'GBP' as currency
        ,customer_updates
        ,count(amount) as total_no_payments
        ,coalesce(sum(amount), 0) as total_amount
      from customer_payment
      group by
        last_updated
        ,customer_updates
        ,current_occupation
        ,date_of_birth
        ,customer_created_at
        ,currency
    entities:
      - customer_id
    multi_stage_engine: true
feature_sets:
  transactions_6h:
    features:
      - payment_6h_batch
      - atm_withdrawal_6h
