apiVersion: v1
kind: ConfigMap
metadata:
  name: dbt
data:
  profiles.yml: |
    warehouse:
      target: dev
      outputs:
        dev:
          type: trino
          method: none
          host: trino.default.svc.cluster.local
          database: polaris
          schema: features
          port: 8080
          user: test.user
