apiVersion: batch/v1
kind: Job
metadata:
  name: consumer-simulation
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      containers:
        - name: consumer-simulation
          image: simulation:latest
          imagePullPolicy: Never
          resources:
            requests:
              cpu: "10m"
              memory: "64Mi"
          env:
            - name: KAFKA_BROKER
              value: "redpanda-0.redpanda.default.svc.cluster.local:9093"
            - name: SCHEMA_REGISTRY_URL
              value: "http://redpanda-0.redpanda.default.svc.cluster.local:8081"
            - name: FEATURE_STORE_URL
              value: "http://feature-store.default.svc.cluster.local"
      restartPolicy: OnFailure
      initContainers:
        - name: wait-for-schema-registry
          image: curlimages/curl:8.16.0
          resources:
            requests:
              cpu: 1m
              memory: 8Mi
            limits:
              cpu: 10m
              memory: 16Mi
          env:
            - name: HEALTH_URL
              value: http://redpanda:8081/subjects
          command:
            - sh
            - -c
            - |
              until curl -fsS "$HEALTH_URL" >/dev/null; do
                sleep 5
              done
