apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: consumer-simulation
  namespace: metrics
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: consumer-simulation
  endpoints:
    - port: metrics
      path: /metrics
      interval: 5s
