apiVersion: v1
kind: Service
metadata:
  name: freshness-probe
  labels:
    app: freshness-probe
spec:
  selector:
    app: freshness-probe
  ports:
    - name: metrics
      port: 8000
      targetPort: metrics