apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - consumer-simulation-job.yaml
  - freshness-probe-deployment.yaml
  - freshness-probe-service.yaml
  - freshness-probe-service-monitor.yaml
