features:
  atm_withdrawal_6h:
    sql: |
      SELECT
        account_id,
        customer_id,
        card_id,
        SUM(amount) as total_amount,
        COUNT(*) as total_tx
      FROM atm_withdrawal
      WHERE account_id = (%(account_id)d)
        AND customer_id = (%(customer_id)d)
        AND card_id = (%(card_id)d)
        AND "timestamp" >= NOW() - 6 * 60 * 60 * 1000
      GROUP BY account_id, customer_id, card_id
    entities:
      - account_id
      - customer_id
      - card_id
  login_attempted_6h:
    sql: |
      SELECT
          customer_id,
          device_id,
          COUNT(*) AS no_attempts,
          DISTINCTCOUNT(country) AS no_countries,
          ARRAY_AGG(country, 'STRING', true) AS countires
      FROM login_attempted
      WHERE 
          "timestamp" > NOW() - 6 * 60 * 60 * 1000
          AND customer_id = (%(customer_id)d)
          AND device_id = (%(device_id)d)
      GROUP BY customer_id, device_id
    entities:
      - customer_id
      - device_id
  payment_6h_batch:
    sql: |
      SELECT *
      FROM payment_6h_batch
      WHERE account_id = (%(account_id)d)
      AND card_id = (%(card_id)d)
    entities:
      - account_id
      - card_id
feature_sets:
  transactions_6h:
    features:
      - payment_6h
      - atm_withdrawal_6h
