features:
  atm_withdrawal_6h:
    sql: |
      SELECT
        account_id,
        customer_id,
        card_id,
        SUM(amount) as total_amount,
        COUNT(*) as total_tx
      FROM atm_withdrawal
      WHERE account_id = (%(account_id)s)
        AND customer_id = (%(customer_id)s)
        AND card_id = (%(card_id)s)
        AND "timestamp" >= NOW() - 6 * 60 * 60 * 1000
      GROUP BY account_id, customer_id, card_id
    entities:
      - account_id
      - customer_id
      - card_id
  login_attempted_6h:
    sql: |
      SELECT
          customer_id,
          device_id,
          COUNT(*) AS no_attempts,
          DISTINCTCOUNT(country) AS no_countries,
          ARRAY_AGG(country, 'STRING', true) AS countires
      FROM login_attempted
      WHERE 
          "timestamp" > NOW() - 6 * 60 * 60 * 1000
          AND customer_id = (%(customer_id)s)
          AND device_id = (%(device_id)s)
      GROUP BY customer_id, device_id
    entities:
      - customer_id
      - device_id
  payment_6h_batch:
    sql: |
      SELECT *
      FROM payment_6h_batch
      WHERE account_id = (%(account_id)s)
      AND card_id = (%(card_id)s)
    entities:
      - account_id
      - card_id
  payment_6h:
    sql: |
      with transactions as (
        select
            id
            ,"timestamp"
            ,account_id
            ,amount
            ,currency
            ,'WITHDRAWAL' as transaction_type
        from atm_withdrawal
        where account_id = (%(account_id)s)
        and "timestamp" >= NOW() - 6 * 60 * 60 * 1000
        union all
        select
            id
            ,"timestamp"
            ,account_id
            ,amount
            ,currency
            ,'CARD_PAYMENT' as transaction_type
        from payment_authorised
        where account_id = (%(account_id)s)
        and "timestamp" >= NOW() - 6 * 60 * 60 * 1000
        union all
        select
            id
            ,"timestamp"
            ,cast(destination_account_id as bigint) as account_id
            ,amount
            ,currency
            ,'TRANSFER' as transaction_type
        from transfer_completed
        where destination_account_id = (%(account_id)s)
        and "timestamp" >= NOW() - 6 * 60 * 60 * 1000
        union all
        select
            id
            ,"timestamp"
            ,cast(source_account_id as bigint) as account_id
            ,amount
            ,currency
            ,'TRANSFER' as transaction_type
        from transfer_completed
        where source_account_id = (%(account_id)s)
        and "timestamp" >= NOW() - 6 * 60 * 60 * 1000
      )
      select
        count(*) as tx_count
        ,sum(amount) as tx_sum
        ,max(amount) as tx_max
        ,min(amount) as tx_min
        
        ,sum(case when transaction_type = 'WITHDRAWAL' then 1 else 0 end) as withdrawal_count
        ,sum(case when transaction_type = 'WITHDRAWAL' then amount else 0 end) as withdrawal_sum
        ,max(case when transaction_type = 'WITHDRAWAL' then amount end) as withdrawal_max
        ,min(case when transaction_type = 'WITHDRAWAL' then amount end) as withdrawal_min
    
        ,sum(case when transaction_type = 'CARD_PAYMENT' then 1 else 0 end) as card_count
        ,sum(case when transaction_type = 'CARD_PAYMENT' then amount else 0 end) as card_sum
        ,max(case when transaction_type = 'CARD_PAYMENT' then amount end) as card_max
        ,min(case when transaction_type = 'CARD_PAYMENT' then amount end) as card_min
        
        ,sum(case when transaction_type = 'TRANSFER' then 1 else 0 end) as transfer_count
        ,sum(case when transaction_type = 'TRANSFER' then amount else 0 end) as transfer_sum
        ,max(case when transaction_type = 'TRANSFER' then amount end) as transfer_max
        ,min(case when transaction_type = 'TRANSFER' then amount end) as transfer_min
      from transactions;
    entities:
      - account_id
    multi_stage_engine: true
feature_sets:
  transactions_6h:
    features:
      - payment_6h_batch
      - atm_withdrawal_6h
